### ISSUE TITLE
tag 0.1.7 composer.json version number issue

### ISSUE THREAD

**Issue by HashDefineElectronics** [andelux/mailgun-magento2#4]
Hi,

The tag 0.1.7 [composer.json](https://github.com/andelux/mailgun-magento2/blob/0.1.7/composer.json) file needs updating so that the version number matches its tag version. 

Its currently set to 0.1.6 which means that composer will ignore it during updates/install.  At the moment, you have to set your module requirement version to dev-master in order to get the critical bug fix in version 0.1.7.

Thank you in advance,

-- Ron

**Comment by javierperezm** [comment]
Solved!
